version: '2'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: express_db
      MYSQL_USER: express_db
      MYSQL_PASSWORD: express_db

  web:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      PORT: 3000
